<?php

namespace app\coupon\controller;

use think\Controller;
use think\Request;
use think\Session;

class Base extends Controller
{

    /**
     * 判断是否已经登录
     */
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        if (!(Session::has("business"))) {
            Redirects('coupon/login');
        }
    }

    /**
     * 不存在控制器
     * @return mixed
     */
    public function _empty()
    {
        return abort(404, '页面不存在');
    }
}
