<?php

namespace app\superadmin\controller;

use think\Request;
use think\Controller;

class LoginAuth extends Controller
{
//    public function _initialize ()
//    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
//        if(!Session::has("superAdmin")){
//            $this->error("'对不起,您还没有登录!请先登录再进行浏览'",Url("superAdmin/login"));
//        }
//    }
    public function _empty()
    {
        return abort(404,'页面不存在');
    }
}
