<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2018 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: liu21st <liu21st@gmail.com>
// +----------------------------------------------------------------------

use think\Route;
#总后台管理
Route::get('mobile/', 'mobile/index/index'); // 定义GET请求路由规则
Route::get('mobile/login', 'mobile/login/index');
Route::post('mobile/verif_login', 'mobile/login/verif_login');
Route::get('mobile/sendmsg', 'mobile/index/send');
Route::get('mobile/parking_info', 'mobile/index/parking_info');
Route::get('mobile/wechats', 'mobile/wechats/index');
Route::get('home/home', 'home/home/home');
Route::get('home/getUrls', 'home/home/getUrls');
Route::get('admin/login', 'admin/login/index');
Route::get('admin/sendcode', 'admin/login/sendCode');
Route::post('admin/loginUserVerif', 'admin/login/loginUserVerif');
Route::get('admin/wxqrlogin', 'admin/login/wxqrlogin');//微信扫码登录
Route::get('admin/wxlogin', 'admin/login/wxlogin');//微信授权登录
Route::get('admin/info', 'admin/index/info');
Route::get('admin/index', 'admin/index/index');
Route::get('admin/dashboard', 'admin/index/dashboard');
//角色权限配置
Route::any('admin/rolePermission/index','admin/Rolepermission/index');
Route::any('admin/rolePermission/save','admin/Rolepermission/save');
Route::any('admin/rolePermission/permission_setting','admin/Rolepermission/permission_setting');
Route::any('admin/rolePermission/del','admin/Rolepermission/del');
Route::any('admin/rolePermission/get_menu','admin/Rolepermission/get_menu');
Route::any('admin/rolePermission/save_menu','admin/Rolepermission/save_menu');
Route::any('admin/rolePermission/del_menu','admin/Rolepermission/del_menu');
Route::any('admin/rolePermission/website_manage','admin/Rolepermission/website_manage');
Route::any('admin/rolePermission/save_website','admin/Rolepermission/save_website');
Route::any('admin/rolePermission/del_website','admin/Rolepermission/del_website');
// Route::any('admin/rolePermission/get_menu','admin/Rolepermission/get_menu');

//运营中心-运营管理
Route::any('admin/rolePermission/customer_features','admin/Rolepermission/customer_features');
Route::any('admin/rolePermission/save_customer_features','admin/Rolepermission/save_customer_features');
Route::any('admin/rolePermission/del_customer_features','admin/Rolepermission/del_customer_features');
Route::any('admin/rolePermission/selfuse_features','admin/Rolepermission/selfuse_features');

//后台人员配置
Route::any('admin/userManager/index','admin/Usermanager/index');
Route::any('admin/userManager/save','admin/Usermanager/save');
Route::any('admin/userManager/save','admin/Usermanager/save');
Route::any('admin/userManager/setting_role','admin/Usermanager/setting_role');
//商户管理配置
Route::any('admin/merchantManager/index','admin/Merchantmanager/index');
Route::any('admin/merchantManager/approval','admin/Merchantmanager/approval');#境外文件-审批管理
Route::any('admin/merchantManager/save','admin/Merchantmanager/save');
Route::any('admin/merchantManager/save_info','admin/Merchantmanager/save_info');
Route::any('admin/merchantManager/save_auth','admin/Merchantmanager/save_auth');
Route::any('admin/merchantManager/sendcode','admin/Merchantmanager/sendcode');
Route::any('admin/merchantManager/sendemailcode','admin/Merchantmanager/sendemailcode');
Route::any('admin/merchantManager/log','admin/Merchantmanager/log');
Route::any('admin/merchantManager/log_detail','admin/Merchantmanager/log_detail');
Route::any('admin/merchantManager/ip_index','admin/Merchantmanager/ip_index');
Route::any('admin/merchantManager/save_ip','admin/Merchantmanager/save_ip');
Route::any('admin/merchantManager/del_ip','admin/Merchantmanager/del_ip');
Route::any('admin/merchantManager/ip_same','admin/Merchantmanager/ip_same');
Route::any('admin/merchantManager/data_manage','admin/Merchantmanager/data_manage');
//仓库管理
Route::any('admin/warehouse/warehouse_list','admin/Warehouse/warehouse_list');
Route::any('admin/warehouse/save_warehouse','admin/Warehouse/save_warehouse');
Route::any('admin/warehouse/del_warehouse','admin/Warehouse/del_warehouse');
Route::any('admin/warehouse/terminal_list','admin/Warehouse/terminal_list');
Route::any('admin/warehouse/save_terminal','admin/Warehouse/save_terminal');
Route::any('admin/warehouse/save_freight_config','admin/Warehouse/save_freight_config');
Route::any('admin/warehouse/del_terminal','admin/Warehouse/del_terminal');
Route::any('admin/warehouse/del_printer_express','admin/Warehouse/del_printer_express');//删除打印机的快递支持
Route::any('admin/warehouse/express_inquiry','admin/Warehouse/express_inquiry');//快递查询次数配置
//代码配置
Route::any('admin/basic/base_info','admin/Basic/base_info');
Route::any('admin/basic/code_list','admin/Basic/code_list');
Route::any('admin/basic/areacode_list','admin/Basic/areacode_list');
Route::any('admin/basic/save_currency','admin/Basic/save_currency');#修改/保存法币
Route::any('admin/basic/save_tax','admin/Basic/save_tax');#修改/保存涉税
Route::any('admin/basic/import_taxs','admin/Basic/import_taxs');#修改/保存涉税
Route::any('admin/basic/del_risk','admin/Basic/del_risk');#删除风控管理
Route::any('admin/basic/get_currency','admin/Basic/get_currency');#获取该国法币
Route::any('admin/basic/declare_value_list','admin/Basic/declare_value_list');#个人自用提示-申报货值
Route::any('admin/basic/declare_num_list','admin/Basic/declare_num_list');#个人自用提示-单品数量
Route::any('admin/basic/declare_grosswt_list','admin/Basic/declare_grosswt_list');#个人自用提示-包裹毛重
Route::any('admin/basic/declare_volumn_list','admin/Basic/declare_volumn_list');#个人自用提示-包裹体积
Route::any('admin/basic/declare_post1_list','admin/Basic/declare_post1_list');#商业自用提示-一址多邮
Route::any('admin/basic/declare_post2_list','admin/Basic/declare_post2_list');#商业自用提示-分票多邮
Route::any('admin/basic/declare_post3_list','admin/Basic/declare_post3_list');#商业自用提示-分日多邮
Route::any('admin/basic/get_next_value','admin/Basic/get_next_value');#获取二级类别
Route::any('admin/basic/export_name1','admin/Basic/export_name1');#导出1
Route::any('admin/basic/export_name2','admin/Basic/export_name2');#导出2
Route::any('admin/basic/upload_code','admin/Basic/upload_code');
Route::any('admin/basic/upload_file','admin/Basic/upload_file');
Route::any('admin/basic/search_info','admin/Basic/search_info');
Route::any('admin/basic/view_info','admin/Basic/view_info');
Route::any('admin/basic/save_duty_paragraph','admin/Basic/save_duty_paragraph');
Route::any('admin/systemTips/list','admin/Systemtips/list');#提示配置
Route::any('admin/systemTips/gettableinfo','admin/Systemtips/gettableinfo');#提示配置
//产品配置
Route::any('admin/basic/product_list','admin/Basic/product_list');
Route::any('admin/basic/add_product_list','admin/Basic/add_product_list');
Route::any('admin/basic/see_product','admin/Basic/see_product');
Route::any('admin/basic/del_product','admin/Basic/del_product');
//属性配置
Route::any('admin/basic/value_list','admin/Basic/value_list');
Route::any('admin/basic/save_value_list','admin/Basic/save_value_list');
Route::any('admin/basic/del_value','admin/Basic/del_value');
//须知配置
Route::any('admin/basic/guide_list','admin/Basic/guide_list');

//国家代码管理
Route::any('admin/country/code_list','admin/country/code_list');
Route::any('admin/country/save_code','admin/country/save_code');
Route::any('admin/country/content_list','admin/country/content_list');
Route::any('admin/country/upload_code','admin/country/upload_code');
Route::any('admin/country/upload_code2','admin/country/upload_code2');#检查国地是否存在
Route::any('admin/country/upload_code2_phone','admin/country/upload_code2_phone');#录入时差和电话代码
Route::any('admin/country/export_cname1','admin/country/export_cname1');#导出系统缺少的国地
Route::any('admin/country/export_cname2','admin/country/export_cname2');#导出系统多余的国地
Route::any('admin/country/upload_code3','admin/country/upload_code3');#关联国地
Route::any('admin/country/export_cname3','admin/country/export_cname3');#导出系统查询不到的国地
Route::any('admin/country/del_code','admin/country/del_code');
Route::any('admin/country/value_list','admin/country/value_list');
Route::any('admin/country/save_value','admin/country/save_value');
Route::any('admin/country/del_value','admin/country/del_value');
Route::any('admin/country/get_merchant','admin/country/get_merchant');
Route::any('admin/country/prohibit_list','admin/country/prohibit_list');
Route::any('admin/country/save_prohibit','admin/country/save_prohibit');
Route::any('admin/country/del_prohibit','admin/country/del_prohibit');
Route::any('admin/country/upload_code4','admin/country/upload_code4');#检查各国邮政
Route::any('admin/country/check_post','admin/country/check_post');#点击检查邮政
Route::any('admin/country/upload_file','admin/country/upload_file');#点击检查邮政
//网站内容
Route::any('admin/officialwebsite/crawl_task_list','admin/Officialwebsite/crawl_task_list');#任务管理
Route::any('admin/officialwebsite/save_task','admin/Officialwebsite/save_task');#添加任务
Route::any('admin/officialwebsite/del_task','admin/Officialwebsite/del_task');#删除任务
Route::any('admin/officialwebsite/crawl_content_list','admin/Officialwebsite/crawl_content_list');
Route::any('admin/officialwebsite/add_crawl_content','admin/Officialwebsite/add_crawl_content');
Route::any('admin/officialwebsite/add_label','admin/Officialwebsite/add_label');
Route::any('admin/officialwebsite/add_plain','admin/Officialwebsite/add_plain');
Route::any('admin/officialwebsite/del_plain','admin/Officialwebsite/del_plain');
Route::any('admin/officialwebsite/add_crawl_plain','admin/Officialwebsite/add_crawl_plain');
Route::any('admin/officialwebsite/label_list','admin/Officialwebsite/label_list');
Route::any('admin/officialwebsite/del_label','admin/Officialwebsite/del_label');
Route::any('admin/officialwebsite/crawl_order','admin/Officialwebsite/crawl_order');
Route::any('admin/officialwebsite/crawl_plain','admin/Officialwebsite/crawl_plain');
Route::any('admin/officialwebsite/crawl_content','admin/Officialwebsite/crawl_content');
Route::any('admin/officialwebsite/add_content','admin/Officialwebsite/add_content');
Route::any('admin/officialwebsite/add_diycontent','admin/Officialwebsite/add_diycontent');
Route::any('admin/officialwebsite/del_diycontent','admin/Officialwebsite/del_diycontent');
Route::any('admin/officialwebsite/fake_shelf_diylist','admin/Officialwebsite/fake_shelf_diylist');
Route::any('admin/officialwebsite/fake_shelf_diydetail','admin/Officialwebsite/fake_shelf_diydetail');
Route::any('admin/officialwebsite/batch_launch_diy','admin/Officialwebsite/batch_launch_diy');
Route::any('admin/officialwebsite/crawl_children_content','admin/Officialwebsite/crawl_children_content');
Route::any('admin/officialwebsite/contrast_pfc_detail','admin/Officialwebsite/contrast_pfc_detail');
Route::any('admin/officialwebsite/fake_shelf_list','admin/Officialwebsite/fake_shelf_list');
Route::any('admin/officialwebsite/fake_shelf_detail','admin/Officialwebsite/fake_shelf_detail');
Route::any('admin/officialwebsite/batch_launch','admin/Officialwebsite/batch_launch');
Route::any('admin/officialwebsite/get_module','admin/Officialwebsite/get_module');
Route::any('admin/officialwebsite/get_child_module','admin/Officialwebsite/get_child_module');
Route::any('admin/officialwebsite/pfc_detail','admin/Officialwebsite/pfc_detail');
Route::any('admin/officialwebsite/del_pfc_detail','admin/Officialwebsite/del_pfc_detail');
//网站管理
Route::any('admin/officialwebsite/website_manage_list','admin/Officialwebsite/website_manage_list');
Route::any('admin/officialwebsite/save_gather_website','admin/Officialwebsite/save_gather_website');
Route::any('admin/officialwebsite/base_setting','admin/Officialwebsite/base_setting');
Route::any('admin/officialwebsite/menu_list','admin/Officialwebsite/menu_list');
Route::any('admin/officialwebsite/get_menu','admin/Officialwebsite/get_menu');
Route::any('admin/officialwebsite/save_menu','admin/Officialwebsite/save_menu');
Route::any('admin/officialwebsite/del_menu','admin/Officialwebsite/del_menu');
Route::any('admin/officialwebsite/rotate_list','admin/Officialwebsite/rotate_list');
Route::any('admin/officialwebsite/rotate_save','admin/Officialwebsite/rotate_save');
Route::any('admin/officialwebsite/rotate_del','admin/Officialwebsite/rotate_del');
Route::any('admin/officialwebsite/index_list','admin/Officialwebsite/index_list');//首页导航
Route::any('admin/officialwebsite/index_content_order','admin/Officialwebsite/index_content_order');
Route::any('admin/officialwebsite/save_index_content','admin/Officialwebsite/save_index_content');
Route::any('admin/officialwebsite/del_index_content','admin/Officialwebsite/del_index_content');
Route::any('admin/officialwebsite/get_child_menu','admin/Officialwebsite/get_child_menu');
Route::any('admin/officialwebsite/get_content','admin/Officialwebsite/get_content');
//分销管理
Route::any('admin/distribution/index','admin/Distribution/index');
Route::any('admin/distribution/add_distr','admin/Distribution/add_distr');
Route::any('admin/distribution/distr_commission','admin/Distribution/distr_commission');
Route::any('admin/distribution/distr_restrict','admin/Distribution/distr_restrict');
Route::any('admin/distribution/recruit_method','admin/Distribution/recruit_method');
Route::any('admin/distribution/del_distr','admin/Distribution/del_distr');
Route::any('admin/distribution/apply_distr','admin/Distribution/apply_distr');
Route::any('admin/distribution/order_manage','admin/Distribution/order_manage');
Route::any('admin/distribution/settlement_manage','admin/Distribution/settlement_manage');
Route::any('admin/distribution/orderdetail_list','admin/Distribution/orderdetail_list');
Route::any('admin/distribution/edit_lists','admin/Distribution/edit_lists');
Route::any('admin/distribution/order_list','admin/Distribution/order_list');
Route::any('admin/distribution/edit_olists','admin/Distribution/edit_olists');
Route::any('admin/distribution/notice','admin/Distribution/notice');
Route::any('admin/distribution/add_elist','admin/Distribution/add_elist');
Route::any('admin/distribution/settlement_statistics','admin/Distribution/settlement_statistics');
Route::any('admin/distribution/save_settlement','admin/Distribution/save_settlement');
Route::any('admin/distribution/save_payinfo','admin/Distribution/save_payinfo');
//任务管理
Route::any('admin/task/notice','admin/Task/notice');
Route::any('admin/task/task_manage','admin/Task/task_manage');
Route::any('admin/task/order_info','admin/Task/order_info');
Route::any('admin/task/save','admin/Task/save');
Route::any('admin/task/workorder_list','admin/Task/workorder_list');
Route::any('admin/task/roam','admin/Task/roam');
Route::any('admin/task/edit_workorder','admin/Task/edit_workorder');
Route::any('admin/task/roam_type','admin/Task/roam_type');
Route::any('admin/task/confirm','admin/Task/confirm');
Route::any('admin/task/reject','admin/Task/reject');
//代购管理
Route::any('admin/behalf/logistics_manage','admin/Behalf/logistics_manage');
Route::any('admin/behalf/add_logistics','admin/Behalf/add_logistics');
Route::any('admin/behalf/del_logistics','admin/Behalf/del_logistics');
Route::any('admin/behalf/expnumber_list','admin/Behalf/expnumber_list');
Route::any('admin/behalf/order_manage','admin/Behalf/order_manage');
Route::any('admin/behalf/order_detail','admin/Behalf/order_detail');
Route::any('admin/behalf/make_express','admin/Behalf/make_express');
Route::any('admin/behalf/update_order_express','admin/Behalf/update_order_express');
Route::any('admin/behalf/make_ticket','admin/Behalf/make_ticket');
Route::any('admin/behalf/inventory_manage','admin/Behalf/inventory_manage');
Route::any('admin/behalf/out_inventory','admin/Behalf/out_inventory');
//采购管理
Route::any('admin/purchase/buyer_index','admin/Purchase/buyer_index');
Route::any('admin/purchase/save_buyer','admin/Purchase/save_buyer');
Route::any('admin/purchase/review_buyer','admin/Purchase/review_buyer');
Route::any('admin/purchase/del_buyer','admin/Purchase/del_buyer');
Route::any('admin/purchase/purchase_history','admin/Purchase/purchase_history');
Route::any('admin/purchase/shunt_index','admin/Purchase/shunt_index');
Route::any('admin/purchase/save_shunt','admin/Purchase/save_shunt');
Route::any('admin/purchase/del_shunt','admin/Purchase/del_shunt');
Route::any('admin/purchase/shunt_history','admin/Purchase/shunt_history');
Route::any('admin/purchase/audit_order','admin/Purchase/audit_order');

//购购网管理
Route::any('admin/operaweb/authorization_manage','admin/Operaweb/authorization_manage');#登录页授权配置
Route::any('admin/operaweb/save_authorization','admin/Operaweb/save_authorization');#登录页授权配置
Route::any('admin/operaweb/del_authorization','admin/Operaweb/del_authorization');#登录页授权配置
Route::any('admin/operaweb/newscate_manage','admin/Operaweb/newscate_manage');
Route::any('admin/operaweb/save_newscate','admin/Operaweb/save_newscate');
Route::any('admin/operaweb/del_newscate','admin/Operaweb/del_newscate');
Route::any('admin/operaweb/news_list','admin/Operaweb/news_list');
Route::any('admin/operaweb/add_news','admin/Operaweb/add_news');
Route::any('admin/operaweb/del_news','admin/Operaweb/del_news');
Route::any('admin/operaweb/platform_rule_manage','admin/Operaweb/platform_rule_manage');#平台规则管理-同一类别、关键字
Route::any('admin/operaweb/del_rule','admin/Operaweb/del_rule');#平台规则管理-删除同一类别、关键字
Route::any('admin/operaweb/rule_manage','admin/Operaweb/rule_manage');#平台规则管理-同一类别、关键字列表
Route::any('admin/operaweb/save_platform_rule','admin/Operaweb/save_platform_rule');#新增平台规则
Route::any('admin/operaweb/get_keywords','admin/Operaweb/get_keywords');#获取类别关键词
Route::any('admin/operaweb/hide_rule_manage','admin/Operaweb/hide_rule_manage');#隐藏/显示平台规则
Route::any('admin/operaweb/share_rule_img','admin/Operaweb/share_rule_img');#分享规则链接生成二维码
Route::any('admin/operaweb/rule_type','admin/Operaweb/rule_type');#平台规则-类别列表
Route::any('admin/operaweb/del_rule_type','admin/Operaweb/del_rule_type');#平台规则-删除类别
Route::any('admin/operaweb/save_rule_type','admin/Operaweb/save_rule_type');#平台规则-保存类别
Route::any('admin/operaweb/keywords_list','admin/Operaweb/keywords_list');#平台规则-关键字列表
Route::any('admin/operaweb/del_keywords','admin/Operaweb/del_keywords');#平台规则-删除关键字
Route::any('admin/operaweb/save_keywords','admin/Operaweb/save_keywords');#平台规则-保存关键字
Route::any('admin/operaweb/rule_pdf','admin/Operaweb/rule_pdf');#平台规则-生成pdf
Route::any('admin/operaweb/enterprise_news_manage','admin/Operaweb/enterprise_news_manage');
Route::any('admin/operaweb/save_enterprise_news','admin/Operaweb/save_enterprise_news');
Route::any('admin/operaweb/del_enterprise_news','admin/Operaweb/del_enterprise_news');
Route::any('admin/operaweb/crossnews_manage','admin/Operaweb/crossnews_manage');#跨境新闻
Route::any('admin/operaweb/del_crossborder_news','admin/Operaweb/del_crossborder_news');#跨境新闻-删除
Route::any('admin/operaweb/save_crossborder_news','admin/Operaweb/save_crossborder_news');#跨境新闻-人工输入上架
Route::any('admin/operaweb/shelf_crossborder_news','admin/Operaweb/shelf_crossborder_news');#跨境新闻-手动上架
Route::any('admin/operaweb/qualifications_manage','admin/Operaweb/qualifications_manage');
Route::any('admin/operaweb/add_qualific','admin/Operaweb/add_qualific');
Route::any('admin/operaweb/add_qualific2','admin/Operaweb/add_qualific2');
Route::any('admin/operaweb/del_qualific','admin/Operaweb/del_nqualific');
Route::any('admin/operaweb/friendcate_manage','admin/Operaweb/friendcate_manage');
Route::any('admin/operaweb/add_friendcate','admin/Operaweb/add_friendcate');
Route::any('admin/operaweb/del_friendcate','admin/Operaweb/del_friendcate');
Route::any('admin/operaweb/friend_list','admin/Operaweb/friend_list');
Route::any('admin/operaweb/add_friend','admin/Operaweb/add_friend');
Route::any('admin/operaweb/del_friend','admin/Operaweb/del_friend');
Route::any('admin/operaweb/website_manage','admin/Operaweb/website_manage');
Route::any('admin/operaweb/content_manage','admin/Operaweb/content_manage');
Route::any('admin/operaweb/save_content','admin/Operaweb/save_content');
Route::any('admin/operaweb/del_content','admin/Operaweb/del_content');
Route::any('admin/operaweb/contact_manage','admin/Operaweb/contact_manage');
Route::any('admin/operaweb/save_contact','admin/Operaweb/save_contact');
Route::any('admin/operaweb/del_contact','admin/Operaweb/del_contact');
Route::any('admin/operaweb/rotate_manage','admin/Operaweb/rotate_manage');
Route::any('admin/operaweb/save_rotate','admin/Operaweb/save_rotate');
Route::any('admin/operaweb/del_rotate','admin/Operaweb/del_rotate');
Route::any('admin/operaweb/rotate_inner','admin/Operaweb/rotate_inner');
Route::any('admin/operaweb/save_rotateinner','admin/Operaweb/save_rotateinner');
Route::any('admin/operaweb/del_rotateinner','admin/Operaweb/del_rotateinner');
Route::any('admin/operaweb/menu_manage','admin/Operaweb/menu_manage');
Route::any('admin/operaweb/save_menu','admin/Operaweb/save_menu');
Route::any('admin/operaweb/home_setting','admin/Operaweb/home_setting');
Route::any('admin/operaweb/save_home','admin/Operaweb/save_home');
Route::any('admin/operaweb/del_home','admin/Operaweb/del_home');
Route::any('admin/operaweb/get_nextNavbar','admin/Operaweb/get_nextNavbar');
Route::any('admin/operaweb/del_menu','admin/Operaweb/del_menu');
Route::any('admin/operaweb/message_manage','admin/Operaweb/message_manage');
Route::any('admin/operaweb/save_message','admin/Operaweb/save_message');
Route::any('admin/operaweb/del_message','admin/Operaweb/del_message');
Route::any('admin/operaweb/website_user','admin/Operaweb/website_user');#账户管理-会员
Route::any('admin/operaweb/website_merch','admin/Operaweb/website_merch');#账户管理-注册商户
Route::any('admin/operaweb/diy_merch','admin/Operaweb/diy_merch');#账户管理-接口商户
Route::any('admin/operaweb/save_diy_merch','admin/Operaweb/save_diy_merch');#账户管理-保存接口商户
Route::any('admin/operaweb/del_diy_merch','admin/Operaweb/del_diy_merch');#账户管理-删除接口商户
Route::any('admin/operaweb/baseinfo','admin/Operaweb/baseinfo');#账户管理-海外审批
Route::any('admin/operaweb/connect_app','admin/Operaweb/connect_app');#账户管理-关联应用
Route::any('admin/operaweb/distr_manage','admin/Operaweb/distr_manage');#账户管理-分销管理
Route::any('admin/operaweb/order_sure','admin/Operaweb/order_sure');#账户管理-发起订单
Route::any('admin/operaweb/save_ordersure','admin/Operaweb/save_ordersure');
Route::any('admin/operaweb/bill_sure','admin/Operaweb/bill_sure');#账户管理-发起账单
Route::any('admin/operaweb/set_usermerch','admin/Operaweb/set_usermerch');#账户管理-配置为商户
Route::any('admin/operaweb/save_billsure','admin/Operaweb/save_billsure');
Route::any('admin/operaweb/account_list','admin/Operaweb/account_list');#收付管理-账户配置列表
Route::any('admin/operaweb/save_account','admin/Operaweb/save_account');#添加账户
Route::any('admin/operaweb/del_account','admin/Operaweb/del_account');#删除账户
Route::any('admin/operaweb/collect','admin/Operaweb/collect');#账户管理-发起收款列表
Route::any('admin/operaweb/save_collect','admin/Operaweb/save_collect');#账户管理-发起收款
Route::any('admin/operaweb/collect_tosure','admin/Operaweb/collect_tosure');#账户管理-收款待确认列表
Route::any('admin/operaweb/collect_detail','admin/Operaweb/collect_detail');#账户管理-收款待确认列表详情
Route::any('admin/operaweb/collect_process','admin/Operaweb/collect_process');#账户管理-收款进度列表
Route::any('admin/operaweb/withdraw_list','admin/Operaweb/withdraw_list');#账户管理-提款列表
Route::any('admin/operaweb/withdraw_detail','admin/Operaweb/withdraw_detail');#账户管理-提款详情
Route::any('admin/operaweb/analysis','admin/Operaweb/analysis');#账户管理-流水分析
Route::any('admin/operaweb/set_gpt','admin/Operaweb/set_gpt');#GPT访问配置
Route::any('admin/operaweb/set_usergpt','admin/Operaweb/set_usergpt');#GPT访问配置
Route::any('admin/operaweb/buss_list','admin/Operaweb/buss_list');#业务配置列表
Route::any('admin/operaweb/save_buss','admin/Operaweb/save_buss');#保存业务
Route::any('admin/operaweb/del_buss','admin/Operaweb/del_buss');#删除业务
Route::any('admin/operaweb/feedesc_list','admin/Operaweb/feedesc_list');#收费说明列表
Route::any('admin/operaweb/save_feedesc','admin/Operaweb/save_feedesc');#保存收费说明
Route::any('admin/operaweb/del_feedesc','admin/Operaweb/del_feedesc');#删除收费说明
Route::any('admin/operaweb/inquiry_list','admin/Operaweb/inquiry_list');#询价表单列表
Route::any('admin/operaweb/import_template','admin/Operaweb/import_template');#表单列表-导入询价或报价的模板
Route::any('admin/operaweb/save_inquiry','admin/Operaweb/save_inquiry');#保存询价表单
Route::any('admin/operaweb/del_inquiry','admin/Operaweb/del_inquiry');#删除询价表单
Route::any('admin/operaweb/generate_inquiry','admin/Operaweb/generate_inquiry');#生成询价
Route::any('admin/operaweb/reminder','admin/Operaweb/reminder');#催单
Route::any('admin/operaweb/share_img','admin/Operaweb/share_img');#生成分享图片
Route::any('admin/operaweb/quote_list','admin/Operaweb/quote_list');#报价表单列表
Route::any('admin/operaweb/save_quote','admin/Operaweb/save_quote');#保存报价表单
Route::any('admin/operaweb/del_quote','admin/Operaweb/del_quote');#删除报价表单
Route::any('admin/operaweb/inquiry_order','admin/Operaweb/inquiry_order');#询价管理中心
Route::any('admin/operaweb/inquiry_order_detail','admin/Operaweb/inquiry_order_detail');#询价管理中心-询价单详情
Route::any('admin/operaweb/share_inquiry','admin/Operaweb/share_inquiry');#询价管理中心-分享询价
Route::any('admin/operaweb/share_inquiry_log','admin/Operaweb/share_inquiry_log');#询价管理中心-分享询价记录
Route::any('admin/operaweb/quote_order','admin/Operaweb/quote_order');#报价管理中心
Route::any('admin/operaweb/quote_order_detail','admin/Operaweb/quote_order_detail');#报价管理中心-报价详情
Route::any('admin/operaweb/notice_buyer','admin/Operaweb/notice_buyer');#报价管理中心-通知买家
Route::any('admin/operaweb/get_quotetext','admin/Operaweb/get_quotetext');#报价管理中心-获取选择的报价文本
Route::any('admin/operaweb/save_quotetext','admin/Operaweb/save_quotetext');#报价管理中心-保存修改的报价文本
Route::any('admin/operaweb/quote_order_chat','admin/Operaweb/quote_order_chat');#报价管理中心-获取报价聊天记录
Route::any('admin/operaweb/msg_manage','admin/Operaweb/msg_manage');#消息管理
Route::any('admin/operaweb/save_msg','admin/Operaweb/save_msg');#消息管理
Route::any('admin/operaweb/del_msg','admin/Operaweb/del_msg');#消息管理
Route::any('admin/operaweb/disease_manage','admin/Operaweb/disease_manage');#疾病管理
Route::any('admin/operaweb/medical_manage','admin/Operaweb/medical_manage');#药品管理
Route::any('admin/operaweb/discovery_manage','admin/Operaweb/discovery_manage');#发现管理

//集运系统管理
//*集运配置
Route::any('centralize/managemenber/menu_list','centralize/Managemenber/menu_list');//权限配置
Route::any('centralize/managemenber/role_lists','centralize/Managemenber/role_lists');//角色配置
Route::any('centralize/managemenber/person_lists','centralize/Managemenber/person_lists');//用户配置
Route::any('centralize/managemenber/cargo_lists','centralize/Managemenber/cargo_lists');//货物属性配置
//*基础配置
Route::any('centralize/index/rotation','centralize/Index/rotation');//商城和集运首页轮播图
Route::any('centralize/index/rotation_save','centralize/Index/rotation_save');
Route::any('centralize/index/rotation_del','centralize/Index/rotation_del');
Route::any('centralize/index/notice','centralize/Index/notice');//集运首页公告
Route::any('centralize/index/notice_save','centralize/Index/notice_save');
Route::any('centralize/index/notice_del','centralize/Index/notice_del');
Route::any('centralize/index/embargo','centralize/Index/embargo');//禁运列表
Route::any('centralize/index/embargo','centralize/Index/embargo');//集运教学
Route::any('centralize/index/user_agreement','centralize/Index/user_agreement');//用户协议
Route::any('centralize/index/consolidation_agreement','centralize/Index/consolidation_agreement');//集运协议
Route::any('centralize/index/instruction_order','centralize/Index/instruction_order');//下单须知
Route::any('centralize/index/about','centralize/Index/about');//关于我们
Route::any('centralize/index/news','centralize/Index/news');//新闻列表
Route::any('centralize/index/news_save','centralize/Index/news_save');
Route::any('centralize/index/news_del','centralize/Index/news_del');
Route::any('centralize/index/news_type','centralize/Index/news_type');//最新动态分类
Route::any('centralize/index/news_type_save','centralize/Index/news_type_save');
Route::any('centralize/index/news_type_del','centralize/Index/news_type_del');
Route::any('centralize/index/service_list','centralize/Index/service_list');//增值服务
Route::any('centralize/index/save_service','centralize/Index/save_service');
Route::any('centralize/index/del_service','centralize/Index/del_service');
Route::any('centralize/index/warehouse','centralize/Index/warehouse');//仓库地址
Route::any('centralize/index/warehouse_save','centralize/Index/warehouse_save');
Route::any('centralize/index/warehouse_del','centralize/Index/warehouse_del');
Route::any('centralize/index/integral_rule','centralize/Index/integral_rule');//积分规则
Route::any('centralize/index/commission','centralize/Index/commission');//分销商佣金配置
Route::any('centralize/index/pay_param','centralize/Index/pay_param');//支付参数配置
Route::any('centralize/index/pick_up_point','centralize/Index/pick_up_point');//提货点配置
Route::any('centralize/index/pick_up_point_save','centralize/Index/pick_up_point_save');
Route::any('centralize/index/pick_up_point_del','centralize/Index/pick_up_point_del');
Route::any('centralize/index/balance','centralize/Index/balance');//配置余额充值
Route::any('centralize/index/balance_save','centralize/Index/balance_save');//配置余额充值
Route::any('centralize/index/balance_del','centralize/Index/balance_del');//配置余额充值
Route::any('centralize/index/package_manage','centralize/Index/package_manage');//包裹管理列表
Route::any('centralize/index/edit_booking','centralize/Index/edit_booking');//包裹管理列表-修改订仓
Route::any('centralize/index/delaypay_list','centralize/Index/delaypay_list');//赊账管理列表
Route::any('centralize/index/sure_delaypay','centralize/Index/sure_delaypay');//确认赊账
Route::any('centralize/index/reject_delaypay','centralize/Index/reject_delaypay');//拒绝赊账
Route::any('centralize/index/prohibit_package_list','centralize/Index/prohibit_package_list');//禁限类包裹管理列表
Route::any('centralize/index/package_info','centralize/Index/package_info');//包裹详情
Route::any('centralize/index/sure_prohibit_package','centralize/Index/sure_prohibit_package');//确认赊账
Route::any('centralize/index/reject_prohibit_package','centralize/Index/reject_prohibit_package');//拒绝赊账
//*集运营销
Route::any('centralize/index/extra_value_line','centralize/Index/extra_value_line');//超值路线
Route::any('centralize/index/extra_value_line_save','centralize/Index/extra_value_line_save');
Route::any('centralize/index/extra_value_line_del','centralize/Index/extra_value_del');
Route::any('centralize/index/complaint','centralize/Index/complaint');//投诉建议
Route::any('centralize/index/complaint_info','centralize/Index/complaint_info');
Route::any('centralize/index/complaint_del','centralize/Index/complaint_del');
Route::any('centralize/index/coupon','centralize/Index/coupon');//优惠券
Route::any('centralize/index/coupon_save','centralize/Index/coupon_save');
Route::any('centralize/index/coupon_del','centralize/Index/coupon_del');
//*运单管理
Route::any('centralize/index/waybill_list','centralize/Index/waybill_list');
Route::any('centralize/index/save_waybill','centralize/Index/save_waybill');
Route::any('centralize/index/del_waybill','centralize/Index/del_waybill');
Route::any('centralize/index/get_postal_rule','centralize/Index/get_postal_rule');
Route::any('centralize/index/share_waybill','centralize/Index/share_waybill');
Route::any('centralize/index/export_waybill','centralize/Index/export_waybill');
Route::any('centralize/index/export_waybill_pdf','centralize/Index/export_waybill_pdf');
Route::any('centralize/index/export_waybill_exl','centralize/Index/export_waybill_exl');
Route::any('centralize/index/get_qrcode','centralize/Index/get_qrcode');#获取集运商二维码，运营商打开后再微信转发
//*集运流程管理
Route::any('centralize/index/gather_process_manage','centralize/Index/gather_process_manage');
Route::any('centralize/index/save_process','centralize/Index/save_process');
Route::any('centralize/index/del_process','centralize/Index/del_process');
Route::any('centralize/index/child_process','centralize/Index/child_process');
//*资讯中心管理
Route::any('centralize/index/enterprise_news_manage','centralize/Index/enterprise_news_manage');#集运动态管理
Route::any('centralize/index/save_enterprise_news','centralize/Index/save_enterprise_news');
Route::any('centralize/index/del_enterprise_news','centralize/Index/del_enterprise_news');
Route::any('centralize/index/crossnews_manage','centralize/Index/crossnews_manage');#集运新闻管理
Route::any('centralize/index/del_crossborder_news','centralize/Index/del_crossborder_news');#跨境新闻-删除
Route::any('centralize/index/save_crossborder_news','centralize/Index/save_crossborder_news');#跨境新闻-人工输入上架
Route::any('centralize/index/shelf_crossborder_news','centralize/Index/shelf_crossborder_news');#跨境新闻-手动上架
Route::any('centralize/index/newscate_manage','centralize/Index/newscate_manage');#集运政策管理
Route::any('centralize/index/save_newscate','centralize/Index/save_newscate');
Route::any('centralize/index/del_newscate','centralize/Index/del_newscate');
Route::any('centralize/index/news_list','centralize/Index/news_list');
Route::any('centralize/index/add_news','centralize/Index/add_news');
Route::any('centralize/index/del_news','centralize/Index/del_news');#删除集运政策
Route::any('centralize/index/services_manage','centralize/Index/services_manage');#服务描述管理
Route::any('centralize/index/rule_manage','centralize/Index/rule_manage');#规则确认管理
Route::any('centralize/index/save_rule','centralize/Index/save_rule');#保存规则确认
Route::any('centralize/index/del_rule','centralize/Index/del_rule');#删除规则确认
Route::any('centralize/index/rule_log','centralize/Index/rule_log');#规则确认日志
Route::any('centralize/index/save_services','centralize/Index/save_services');
Route::any('centralize/index/del_services','centralize/Index/del_services');
Route::any('centralize/index/platform_services_list','centralize/Index/platform_services_list');
Route::any('centralize/index/save_platform_services_list','centralize/Index/save_platform_services_list');
Route::any('centralize/index/del_platform_services_list','centralize/Index/del_platform_services_list');
Route::any('centralize/index/evaluate_list','centralize/Index/evaluate_list');

//Route::any('centralize/index/set_country','centralize/Index/set_country');
//Route::any('centralize/index/set_line','centralize/Index/set_line');
//*会员列表
Route::any('centralize/member/member_lists','centralize/Member/lists');//会员列表
Route::any('centralize/member/member_info','centralize/Member/member_info');
Route::any('centralize/member/member_del','centralize/Member/member_del');
Route::any('centralize/member/member_data_detail','centralize/Member/member_data_detail');
Route::any('centralize/member/member_grade_list','centralize/Member/member_grade_list');//会员等级列表
Route::any('centralize/member/member_grade_save','centralize/Member/member_grade_save');
Route::any('centralize/member/member_grade_del','centralize/Member/member_grade_del');
Route::any('centralize/member/member_grade_detail','centralize/Member/member_grade_detail');//会员等级购买明细
//*分销商列表
Route::any('centralize/distributor/lists','centralize/Distributor/lists');//分销商列表
Route::any('centralize/distributor/commission_detail','centralize/Distributor/commission_detail');
Route::any('centralize/distributor/child_detail','centralize/Distributor/child_detail');
Route::any('centralize/distributor/withdrawal_apply_list','centralize/Distributor/withdrawal_apply_list');
Route::any('centralize/distributor/withdraw_apply','centralize/Distributor/withdraw_apply');
//*集运订单
Route::any('centralize/centralizeorder/no_warehouse','centralize/Centralizeorder/no_warehouse');//未入库列表
Route::any('centralize/centralizeorder/no_warehouse_check','centralize/Centralizeorder/no_warehouse_check');
Route::any('centralize/centralizeorder/parcel_order_detail','centralize/Centralizeorder/parcel_order_detail');
Route::any('centralize/centralizeorder/in_warehouse','centralize/Centralizeorder/in_warehouse');
Route::any('centralize/centralizeorder/packing','centralize/Centralizeorder/packing');
Route::any('centralize/centralizeorder/packing_check','centralize/Centralizeorder/packing_check');
Route::any('centralize/centralizeorder/parcel_merge_order_detail','centralize/Centralizeorder/parcel_merge_order_detail');
Route::any('centralize/centralizeorder/all_order','centralize/Centralizeorder/all_order');//待付款、待发货、已发货、待评价（已完成）
Route::any('centralize/centralizeorder/deliver_goods','centralize/Centralizeorder/deliver_goods');//发货
Route::any('centralize/centralizeorder/return_goods_apply','centralize/Centralizeorder/return_goods_apply');//处理退换货申请
Route::any('centralize/centralizeorder/no_main_part','centralize/Centralizeorder/no_main_part');//无件住认领
Route::any('centralize/centralizeorder/no_main_part_save','centralize/Centralizeorder/no_main_part_save');
Route::any('centralize/centralizeorder/no_main_part_del','centralize/Centralizeorder/no_main_part_del');

/**
 * 集运系统配置用户功能
 **/
Route::any('centralize/managemenber/menu_list','centralize/Managemenber/menu_list');//权限菜单列表
Route::any('centralize/managemenber/save_menu','centralize/Managemenber/save_menu');//保存权限菜单
Route::any('centralize/managemenber/del_menu','centralize/Managemenber/del_menu');//删除权限

Route::any('centralize/managemenber/role_lists','centralize/Managemenber/role_lists');//角色列表
Route::any('centralize/managemenber/save_role','centralize/Managemenber/save_role');//保存角色
Route::any('centralize/managemenber/del_role','centralize/Managemenber/del_role');//删除角色

//*业务账单管理
Route::any('admin/business/overdue_setting','admin/Business/overdue_setting');//付款逾期设置
Route::any('admin/business/buss_list','admin/Business/buss_list');//业务类别列表
Route::any('admin/business/save_buss','admin/Business/save_buss');//保存业务
Route::any('admin/business/del_buss','admin/Business/del_buss');//删除业务
Route::any('admin/business/save_head','admin/Business/save_head');//保存业务账单表头
Route::any('admin/business/gettableinfo','admin/Business/gettableinfo');//获取指定格式的数据

/**
 * 直邮易小程序
 */
Route::any('centralize/miniprogram/basic_info','centralize/Miniprogram/basic_info');//基础信息配置
Route::any('centralize/miniprogram/menu_list','centralize/Miniprogram/menu_list');//菜单页配置
Route::any('centralize/miniprogram/save_menu','centralize/Miniprogram/save_menu');//保存菜单
Route::any('centralize/miniprogram/del_menu','centralize/Miniprogram/del_menu');//删除菜单
Route::any('centralize/miniprogram/agreement','centralize/Miniprogram/agreement');//协议配置列表
Route::any('centralize/miniprogram/save_agreement','centralize/Miniprogram/save_agreement');//保存协议
Route::any('centralize/miniprogram/del_agreement','centralize/Miniprogram/del_agreement');//删除协议
Route::any('centralize/miniprogram/index','centralize/Miniprogram/index');//首页配置列表
Route::any('centralize/miniprogram/save_index','centralize/Miniprogram/save_index');//保存首页
Route::any('centralize/miniprogram/del_index','centralize/Miniprogram/del_index');//删除首页
Route::any('centralize/miniprogram/message','centralize/Miniprogram/message');//消息列表
Route::any('centralize/miniprogram/save_message','centralize/Miniprogram/save_message');//保存消息
Route::any('centralize/miniprogram/del_message','centralize/Miniprogram/del_message');//删除消息
Route::any('centralize/miniprogram/campaign_opera_list','centralize/Miniprogram/campaign_opera_list');//活动操作教程列表
Route::any('centralize/miniprogram/save_campaign_opera','centralize/Miniprogram/save_campaign_opera');//保存教程
Route::any('centralize/miniprogram/del_campaign_opera','centralize/Miniprogram/del_campaign_opera');//删除教程


#官网首页
Route::get('index', 'index/Index/index'); // 定义GET请求路由规则
Route::get('index/rotate_detail', 'index/Index/rotate_detail');
Route::get('index/detail', 'index/Index/detail');
Route::any('index/package_tracking', 'index/Index/package_tracking');
Route::any('index/price_search', 'index/Index/price_search');
Route::any('index/line_list', 'index/Index/line_list');
Route::any('index/line_detail', 'index/Index/line_detail');
Route::any('index/price_detail', 'index/Index/price_detail');
Route::any('index/introduce', 'index/Index/introduce');
Route::any('index/advice', 'index/Index/advice');
Route::any('index/hscode', 'index/Index/hscode');
Route::any('index/leave_contact', 'index/Index/leave_contact');

/**
 * 商城管理
 */
Route::any('admin/shopping/index','admin/shopping/index');
Route::any('admin/shopping/import_guide_content','admin/shopping/import_guide_content');
Route::any('admin/shopping/save_value','admin/shopping/save_value');
Route::any('admin/shopping/del_value','admin/shopping/del_value');
Route::any('admin/shopping/value_list','admin/shopping/value_list');
Route::any('admin/shopping/activity_index','admin/shopping/activity_index');
Route::any('admin/shopping/save_activity','admin/shopping/save_activity');
Route::any('admin/shopping/del_activity','admin/shopping/del_activity');
Route::any('admin/shopping/reduction_index','admin/shopping/reduction_index');
Route::any('admin/shopping/save_reduction','admin/shopping/save_reduction');
Route::any('admin/shopping/del_reduction','admin/shopping/del_reduction');
Route::any('admin/shopping/platform_value','admin/shopping/platform_value');
Route::any('admin/shopping/save_platform_value','admin/shopping/save_platform_value');
Route::any('admin/shopping/del_platform_value','admin/shopping/del_platform_value');
Route::any('admin/shopping/get_nextcate','admin/shopping/get_nextcate');
Route::any('admin/shopping/hotbuy_index','admin/shopping/hotbuy_index');//热卖热搜管理
Route::any('admin/shopping/save_hotbuy','admin/shopping/save_hotbuy');//添加热卖热搜
Route::any('admin/shopping/goods_list','admin/shopping/goods_list');//热卖热搜_商品列表
Route::any('admin/shopping/del_hotbuy','admin/shopping/del_hotbuy');//删除热卖热搜
Route::any('admin/shopping/transaction_manage','admin/shopping/transaction_manage');//交易流程
Route::any('admin/shopping/save_transaction','admin/shopping/save_transaction');//交易流程-保存
Route::any('admin/shopping/del_transaction','admin/shopping/del_transaction');//交易流程-删除
Route::any('admin/shopping/statement_manage','admin/shopping/statement_manage');//声明管理
Route::any('admin/shopping/gcate_manage','admin/shopping/gcate_manage');//类别管理
Route::any('admin/shopping/save_gcate','admin/shopping/save_gcate');//类别管理-添加
Route::any('admin/shopping/upload_code','admin/shopping/upload_code');//咨询管理-上传exl
Route::any('admin/shopping/del_gcate','admin/shopping/del_gcate');//类别管理-删除
Route::any('admin/shopping/gcate_child','admin/shopping/gcate_child');//类别管理-管理子类
Route::any('admin/shopping/save_gcatechild','admin/shopping/save_gcatechild');//类别管理-管理子类
Route::any('admin/shopping/del_gcatechild','admin/shopping/del_gcatechild');//类别管理-管理子类
Route::any('admin/shopping/get_catechild','admin/shopping/get_catechild');//类别管理-获取分类
Route::any('admin/shopping/feeback_index','admin/shopping/feeback_index');//反馈管理
Route::any('admin/shopping/feeback_detail','admin/shopping/feeback_detail');//反馈管理
Route::any('admin/shopping/chat_index','admin/shopping/chat_index');//咨询管理
Route::any('admin/shopping/chat_confirm','admin/shopping/chat_confirm');//咨询管理
Route::any('admin/shopping/chat_reject','admin/shopping/chat_reject');//咨询管理
Route::any('admin/shopping/workorder_list','admin/shopping/workorder_list');//咨询管理-工单管理
Route::any('admin/shopping/roam','admin/shopping/roam');//咨询管理-流转工单
Route::any('admin/shopping/get_medicine','admin/shopping/get_medicine');//平台商品属性管理-获取药品分类（处方）
Route::any('admin/shopping/order_manage','admin/shopping/order_manage');//订单管理（平台商品）
Route::any('admin/shopping/other_order_manage','admin/shopping/other_order_manage');//订单管理（其他平台商品）
Route::any('admin/shopping/order_detail','admin/shopping/order_detail');//订单详情
Route::any('admin/shopping/base_setting','admin/shopping/base_setting');//基础配置
Route::any('admin/shopping/rotate_manage','admin/shopping/rotate_manage');//轮播图管理
Route::any('admin/shopping/save_rotate','admin/shopping/save_rotate');//保存轮播图
Route::any('admin/shopping/del_rotate','admin/shopping/del_rotate');//删除轮播图
Route::any('admin/shopping/frame_manage','admin/shopping/frame_manage');//弹框管理
Route::any('admin/shopping/save_frame','admin/shopping/save_frame');//保存弹框
Route::any('admin/shopping/del_frame','admin/shopping/del_frame');//删除弹框
Route::any('admin/shopping/save_frameadv','admin/shopping/save_frameadv');//广告图管理
Route::any('admin/shopping/frame_child','admin/shopping/frame_child');//二级菜单管理
Route::any('admin/shopping/business_manage','admin/shopping/business_manage');//业务服务管理
Route::any('admin/shopping/search_manage','admin/shopping/search_manage');//搜索栏管理
Route::any('admin/shopping/message_manage','admin/shopping/message_manage');//信息栏管理
Route::any('admin/shopping/guide_manage','admin/shopping/guide_manage');//导页管理
Route::any('admin/shopping/save_guide','admin/shopping/save_guide');//导页管理
Route::any('admin/shopping/del_guide','admin/shopping/del_guide');//导页管理
Route::any('admin/shopping/footer_manage','admin/shopping/footer_manage');//页脚管理
Route::any('admin/shopping/footer_child','admin/shopping/footer_child');//页脚次级菜单
Route::any('admin/shopping/save_footer','admin/shopping/save_footer');//页脚管理
Route::any('admin/shopping/del_footer','admin/shopping/del_footer');//页脚管理
Route::any('admin/shopping/chat_manage','admin/shopping/chat_manage');//聊天管理
Route::any('admin/shopping/read_chat','admin/shopping/read_chat');//聊天管理
Route::any('admin/shopping/transmit_chat','admin/shopping/transmit_chat');//聊天管理-转发
Route::any('admin/shopping/guideinner_manage','admin/shopping/guideinner_manage');//内页管理
Route::any('admin/shopping/save_guideinner','admin/shopping/save_guideinner');//添加内页
Route::any('admin/shopping/del_guideinner','admin/shopping/del_guideinner');//删除内页
Route::any('admin/shopping/settlement_manage','admin/shopping/settlement_manage');//结算方式管理
Route::any('admin/shopping/save_settlement','admin/shopping/save_settlement');//添加内页
Route::any('admin/shopping/del_settlement','admin/shopping/del_settlement');//删除内页
Route::any('admin/shopping/order_temp_manage','admin/shopping/order_temp_manage');//模板导出管理


/**
 * 处方管理
 */
Route::any('admin/prescription/allergy_manage','admin/Prescription/allergy_manage');
Route::any('admin/prescription/language_manage','admin/Prescription/language_manage');
Route::any('admin/prescription/drug_manage','admin/Prescription/drug_manage');
Route::any('admin/prescription/import_excel','admin/Prescription/import_excel');
Route::any('admin/prescription/send_prescription','admin/Prescription/send_prescription');
Route::any('admin/prescription/prescription_detail','admin/Prescription/prescription_detail');#处方详情
Route::any('admin/prescription/done_prescription','admin/Prescription/done_prescription');
Route::any('admin/prescription/doctor_manage','admin/Prescription/doctor_manage');
Route::any('admin/prescription/save_doctor','admin/Prescription/save_doctor');

#接口模块
Route::any('api/sendemail/index','api/SendEmail/index');
Route::any('api/miniprogram/index','api/Miniprogram/index');
Route::any('api/crawlwebsite/index','api/CrawlWebsite/index');
Route::any('api/uploadfile/index','api/UploadFile/upload_file');
Route::any('api/xfchat/xfyun','api/Xfchat/xfyun');
Route::any('api/xfchat/gogo_news','api/Xfchat/gogo_news');
Route::any('api/gather/getlink','api/Gather/get_link');
Route::any('api/gather/gettableinfo','api/Gather/gettableinfo');
Route::any('api/getgoods/keyword_query','api/GetGoods/keyword_query');
Route::any('api/getgoods/detail_query','api/GetGoods/detail_query');
Route::any('api/getgoods/create_order','api/GetGoods/create_order');
Route::any('api/getgoods/cancel_order','api/GetGoods/cancel_order');
Route::any('api/getgoods/cancel_shop_order','api/GetGoods/cancel_shop_order');
Route::any('api/getgoods/domestic_route','api/GetGoods/domestic_route');
Route::any('api/getgoods/foregin_route','api/GetGoods/foregin_route');
Route::any('api/getgoods/return_order','api/GetGoods/return_order');
Route::any('api/getgoods/return_order_query','api/GetGoods/return_order_query');
Route::any('api/getgoods/get_orderdetail','api/GetGoods/get_orderdetail');
Route::any('api/getgoods/get_orderlog','api/GetGoods/get_orderlog');#获取订单状态变更详情
Route::any('api/getgoods/get_superbuy','api/GetGoods/get_superbuy');#获取superbuy上的热卖商品
Route::any('api/getgoods/get_superbuytest','api/GetGoods/get_superbuytest');#获取superbuy上的热卖商品
Route::any('api/getgoods/get_exchangerate','api/GetGoods/get_exchangerate');#获取汇率
Route::any('api/getgoods/get_worldtime','api/GetGoods/get_worldtime');#获取世界城市
Route::any('api/getgoods/get_worldcity_time','api/GetGoods/get_worldcity_time');#获取世界城市时间
Route::any('api/getgoods/get_hotsearch','api/GetGoods/get_hotsearch');#获取热搜下的商品
Route::any('api/getgoods/get_guide_goods','api/GetGoods/get_guide_goods');#获取导页板块等的商品关键字并爬取
Route::any('api/getgoods/get_empty_keywords','api/GetGoods/get_empty_keywords');#每天获取100个热搜商品，拿5个关键字
Route::any('api/getgoods/get_goods_content','api/GetGoods/get_goods_content');#获取导页内的“关键词”商品
Route::any('api/getgoods/get_errorgoods','api/GetGoods/get_errorgoods');
Route::any('api/getgoods/contact_customer','api/GetGoods/contact_customer');#通知客服人员
Route::any('api/getgoods/get_medical_news','api/GetGoods/get_medical_news');#定时获取药资讯
Route::any('api/getgoods/check_goods_value','api/GetGoods/check_goods_value');#每周六查看商品价格变动
Route::any('api/getgoods/check_lora_data','api/GetGoods/check_lora_data');#每分钟查看有无定时训练数据需要通过webhook推送至本地电脑
Route::any('api/getgoods/check_rag_data','api/GetGoods/check_rag_data');#智能客服将问题id通过webhook推送至本地电脑
Route::any('api/getgoods/translate_word','api/GetGoods/translate_word');#智能客服将问题推给通用千问接口翻译
Route::any('api/getgoods/translate_answer','api/GetGoods/translate_answer');#大模型回答后，中文答案需要翻译成用户指定母语
Route::any('api/getgoods/sync_to_local','api/GetGoods/sync_to_local');#定时向本地电脑通过FRP发送同步数据
Route::any('api/getgoods/get_ip_region','api/GetGoods/get_ip_region');#查询IP归属
Route::any('api/getgoods/log_remind','api/GetGoods/log_remind');#客服提醒配置
Route::any('api/getgoods/get_chat_history','api/GetGoods/get_chat_history');#获取用户当前消息的前5条历史数据
Route::any('api/getgoods/notice_user','api/GetGoods/notice_user');#通知用户
Route::any('api/getgoods/notice_people','api/GetGoods/notice_people');#通知他人
Route::any('api/getgoods/check_sync_data','api/GetGoods/check_sync_data');#定时查看有无同步数据库表任务
Route::any('api/getgoods/now_sync_file_to_local','api/GetGoods/now_sync_file_to_local');#用户体验版-同步文档信息到本地电脑/线上服务器
Route::any('api/getgoods/get_miniprogram_goods_code','api/GetGoods/get_miniprogram_goods_code');#获取商品主题海报图
#阿里云获取数据表接口===start
Route::any('api/getgoods/ay_get_goods','api/GetGoods/ay_get_goods');#获取商品表数据和字段
#阿里云获取数据表接口===end
#paypal===start
Route::any('api/paypal/index','api/Paypal/index');#paypal支付
#paypal===end
##公用方法
###登录api(废弃)
Route::any('api/func/login_api','api/Func/login_api');
Route::any('api/func/generate_member','api/Func/generate_member');
Route::any('api/func/generate_merchant','api/Func/generate_merchant');
Route::any('api/func/get_ip','api/Func/get_ip');
Route::any('api/func/get_area','api/Func/get_area');
Route::any('api/func/get_province','api/Func/get_province');
Route::any('api/func/get_warehouse_info','api/Func/get_warehouse_info');
Route::any('api/func/sync_inventory_to_email','api/Func/sync_inventory_to_email');#同步将库存文件发送至指定邮件
Route::any('api/func/goods_procurement_to_email','api/Func/goods_procurement_to_email');#采购单信息发送至指定邮箱
Route::any('api/func/sure_procurement','api/Func/sure_procurement');#仓库确认拟入库清单信息
Route::any('api/func/combo_goods_to_email','api/Func/combo_goods_to_email');#发送“预打包清单”至指定邮箱
Route::any('api/func/sure_combo','api/Func/sure_combo');#仓库确认预打包清单信息
Route::any('api/func/get_goods_num','api/Func/get_goods_num');#获取各类型的商品规格库存
Route::any('api/func/send_package_to_email','api/Func/send_package_to_email');#发送《拟打包清单》至指定邮箱
Route::any('api/func/sure_package','api/Func/sure_package');#仓库确认拟打包清单信息
Route::any('api/func/send_delivery_to_email','api/Func/send_delivery_to_email');#发送《拟发货清单》至指定邮箱

###快递100快递面单接口
Route::any('api/func/print_order_test','api/Func/print_order_test');
Route::any('api/func/print_order','api/Func/print_order');
Route::any('api/func/print_old','api/Func/print_old');
Route::any('api/func/ele_cancel','api/Func/ele_cancel');
Route::any('api/func/syn_query','api/Func/syn_query');#实时查询所有订单物流轨迹接口
Route::any('api/func/syn_query_single','api/Func/syn_query_single');#实时查询单个订单物流轨迹接口
