<?php

namespace app\index\controller;
use Composer\Command\SearchCommand;
use think\Controller;
use think\Session;
use Util\data\Sysdb;
class CommonController extends Controller
{
    public function _initialize ()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!Session::has("UserResutlt")){
            $this->error("'对不起,您还没有登录!请先登录再进行浏览'",Url("index/login"));
        }
    }
    public function _empty()
    {
        return abort(404,'页面不存在');
    }
    
}